### PR TITLE
Travis-ci to use docker for faster builds

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Not sure why one build failed and the other passed. Any ideas?

**Comment by rendhalver** [comment]
I was under the impression that Travis uses docker containers by default these days and you set sudo = true to disable it.
I could be completely mistaken though.

**Comment by nibalizer** [comment]
recheck

**Comment by nibalizer** [comment]
I'm not sure why PCCI hasn't figured out to recheck this... Will investigate.

**Comment by jyaworski** [comment]
@nibalizer any update?

**Comment by ghoneycutt** [comment]
Since this just has an effect on Travis and Travis said it is good, can we merge?

**Comment by jyaworski** [comment]
Can you rebase? Merge conflicts.

**Comment by ghoneycutt** [comment]
No longer needed. See https://github.com/voxpupuli/puppet-module-puppetboard/blob/master/.travis.yml#L5

**Pull request closed without merging**
