### PR TITLE
group should be a system group

### PR DESCRIPTION
**Pull request by tobru**
it's confusing that the user is declared as a system user, but the group not. this should be consistent.

### CODE REVIEW

**Comment by tobru** [comment]
Better late than never =) I finally did a rebase to the master. If you want I can also rebase to the `3.0.x` branch...

**Comment by nibalizer** [comment]
@tobru yes can you? Thanks!

**Comment by tobru** [comment]
Here we are :recycle: 

```
git rebase upstream/3.0.x
First, rewinding head to replay your work on top of it...
Applying: group should be a system group
Applying: Support adding arbitrary values to settings.py
Applying: Better comment about default value of reports_count
Applying: group should be a system group
Using index info to reconstruct a base tree...
M	manifests/init.pp
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
```

**Comment by ffrank** [comment]
Hi @tobru so do you need help with this? (Sorry for the long silence.)

**Comment by tobru** [comment]
If you want you can add this change manually to the latest branch. Or close this PR... As you like =)

**Comment by nibalizer** [comment]
On further examination, thanks @ffrank, we can actually land this without any change to metadata.json

**Comment by igalic** [comment]
@nibalizer do it so, Number one.

**Comment by jyaworski** [comment]
Hello:

Can this be rebased and squashed, if it's still needed?

**Comment by jyaworski** [comment]
Closing for lack of movement. Please reopen if needed.

**Pull request closed without merging**
