### PR TITLE
Add bounds to dependency versions in metadata

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
What is this PCCI Voting System? Not sure why it is failing.

**Comment by nibalizer** [comment]
Ya... I should fix that. @ghoneycutt ci.puppet.community and puppet-community/pcci

**Comment by nibalizer** [comment]
recheck

**Comment by jyaworski** [comment]
Hello:

I'm going through and looking at all the PCCI stuff. @igalic?

I'm starting to think we should either turn it off or merge despite it.

**Comment by ghoneycutt** [comment]
None of the tests in the PCCI system check what was changed here anyhow. Travis does by validating the metadata and it is happy. Can we merge?

**Comment by jyaworski** [comment]
I went ahead and merged. Thanks @ghoneycutt for the contribution.

**Pull request merged**
